import {Icons} from '../components/Icons';

export const taskCategories = [
  {
    id: 1,
    name: 'Work',
    icon: 'briefcase',
    iconType: Icons.FontAwesome,
    iconColor: '#A9C4F7',
    backgroundColor: '#3B5998',
    activeIconColor: '#FFFFFF',
    activeBackgroundColor: '#1A3E7A',
  },
  {
    id: 2,
    name: 'Home',
    icon: 'home',
    iconType: Icons.FontAwesome,
    iconColor: '#FFF5E6',
    backgroundColor: '#F4A261',
    activeIconColor: '#FFFFFF',
    activeBackgroundColor: '#B56E3A',
  },
  {
    id: 3,
    name: 'Health',
    icon: 'heartbeat',
    iconType: Icons.FontAwesome,
    iconColor: '#CFFFD3',
    backgroundColor: '#4CAF50',
    activeIconColor: '#FFFFFF',
    activeBackgroundColor: '#2D6A29',
  },
  {
    id: 4,
    name: 'Study',
    icon: 'book',
    iconType: Icons.FontAwesome,
    iconColor: '#E5D4FA',
    backgroundColor: '#6A4C93',
    activeIconColor: '#FFFFFF',
    activeBackgroundColor: '#3B2A68',
  },
  {
    id: 5,
    name: 'Reminders',
    icon: 'bell',
    iconType: Icons.FontAwesome,
    iconColor: '#FFE1E1',
    backgroundColor: '#FF6B6B',
    activeIconColor: '#FFFFFF',
    activeBackgroundColor: '#C62828',
  },
  {
    id: 6,
    name: 'Meetings',
    icon: 'video',
    iconType: Icons.Feather,
    iconColor: '#EFF8FF',
    backgroundColor: '#5DADE2',
    activeIconColor: '#FFFFFF',
    activeBackgroundColor: '#1976D2',
  },
  {
    id: 7,
    name: 'Finance',
    icon: 'dollar-sign',
    iconType: Icons.Feather,
    iconColor: '#FFF7E1',
    backgroundColor: '#FFC300',
    activeIconColor: '#000000',
    activeBackgroundColor: '#FFA000',
  },
  {
    id: 8,
    name: 'Shopping',
    icon: 'shopping-cart',
    iconType: Icons.FontAwesome,
    iconColor: '#FFEAE3',
    backgroundColor: '#FF8A65',
    activeIconColor: '#FFFFFF',
    activeBackgroundColor: '#C75B29',
  },
  {
    id: 9,
    name: 'Travel',
    icon: 'plane',
    iconType: Icons.FontAwesome,
    iconColor: '#CCF1EE',
    backgroundColor: '#009688',
    activeIconColor: '#FFFFFF',
    activeBackgroundColor: '#00796B',
  },
  {
    id: 10,
    name: 'Leisure',
    icon: 'gamepad',
    iconType: Icons.FontAwesome,
    iconColor: '#FFEBF1',
    backgroundColor: '#E91E63',
    activeIconColor: '#FFFFFF',
    activeBackgroundColor: '#C2185B',
  },
];
